SELECT B.FLAVOR

FROM (SELECT A.FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (
SELECT FLAVOR, TOTAL_ORDER
FROM FIRST_HALF 
UNION ALL 
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) A
group by A.FLAVOR
ORDER BY TOTAL_ORDER DESC LIMIT 3) B
